# ====================================================
# Publish all joint states
# ====================================================
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# ====================================================
# Panda arm controller
# ====================================================
panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1: { p: 12000, d: 500, i: 0.0, i_clamp: 10000 }
    panda_joint2: { p: 30000, d: 1000, i: 0.02, i_clamp: 10000 }
    panda_joint3: { p: 18000, d: 500, i: 0.01, i_clamp: 1 }
    panda_joint4: { p: 18000, d: 700, i: 0.01, i_clamp: 10000 }
    panda_joint5: { p: 12000, d: 700, i: 0.01, i_clamp: 1 }
    panda_joint6: { p: 7000, d: 500, i: 0.01, i_clamp: 1 }
    panda_joint7: { p: 2000, d: 200, i: 0.0, i_clamp: 1 }

  constraints:
    goal_time: 5.0                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default


# ====================================================
# Panda hand controller
# ====================================================
panda_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_finger_joint1
    - panda_finger_joint2

  gains:
    panda_finger_joint1: { p: 150, d: 1, i: 0, i_clamp: 1 }
    panda_finger_joint2: { p: 150, d: 1, i: 0, i_clamp: 1 }