panda_arm_1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_1_joint1
    - panda_1_joint2
    - panda_1_joint3
    - panda_1_joint4
    - panda_1_joint5
    - panda_1_joint6
    - panda_1_joint7
  gains:
    panda_1_joint1:
      p: 12000
      d: 100
      i: 10
      i_clamp: 1
    panda_1_joint2:
      p: 18000
      d: 100
      i: 10
      i_clamp: 1
    panda_1_joint3:
      p: 18000
      d: 100
      i: 10
      i_clamp: 1
    panda_1_joint4:
      p: 12000
      d: 100
      i: 10
      i_clamp: 1
    panda_1_joint5:
      p: 12000
      d: 100
      i: 10
      i_clamp: 1
    panda_1_joint6:
      p: 7000
      d: 100
      i: 10
      i_clamp: 1
    panda_1_joint7:
      p: 2000
      d: 100
      i: 10
      i_clamp: 1
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0
panda_arm_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_2_joint1
    - panda_2_joint2
    - panda_2_joint3
    - panda_2_joint4
    - panda_2_joint5
    - panda_2_joint6
    - panda_2_joint7
  gains:
    panda_2_joint1:
      p: 12000
      d: 100
      i: 10
      i_clamp: 1
    panda_2_joint2:
      p: 18000
      d: 100
      i: 10
      i_clamp: 1
    panda_2_joint3:
      p: 18000
      d: 100
      i: 10
      i_clamp: 1
    panda_2_joint4:
      p: 12000
      d: 100
      i: 10
      i_clamp: 1
    panda_2_joint5:
      p: 12000
      d: 100
      i: 10
      i_clamp: 1
    panda_2_joint6:
      p: 7000
      d: 100
      i: 10
      i_clamp: 1
    panda_2_joint7:
      p: 2000
      d: 100
      i: 10
      i_clamp: 1
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0
panda_hand_1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_1_finger_joint1
    - panda_1_finger_joint2
  gains:
    panda_1_finger_joint1:
      p: 10000
      d: 100
      i: 1
      i_clamp: 1
    panda_1_finger_joint2:
      p: 10000
      d: 100
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0
panda_hand_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_2_finger_joint1
    - panda_2_finger_joint2
  gains:
    panda_2_finger_joint1:
      p: 10000
      d: 100
      i: 1
      i_clamp: 1
    panda_2_finger_joint2:
      p: 10000
      d: 100
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0